#!/bin/bash

install() {
  # prepare vars
  local name="$PACKAGE_CORE_NAME"

  log::info "[$(timestamp)][package][$name] preparing ..."

  # get system os/arch
  local arch="$PACKAGE_OS_ARCH"
  local kernel="$PACKAGE_OS_KERNEL"
  local platform="$PACKAGE_OS_PLATFORM"
  # usr_bin_dir
  local usr_bin_dir="$PACKAGE_USER_BIN_DIR"
  local tmp_dir="$PACKAGE_TMP_DIR"

  # files
  local tmp_file="$name.tar.gz"
  local bin_file="./${platform}-${arch}/$name"

  # prepare context
  cd $tmp_dir

  # reference: https://github.com/ameshkov/dnslookup/releases
  # example:
  #   https://github.com/ameshkov/dnslookup/releases/download/v1.8.0/dnslookup-darwin-amd64-v1.8.0.tar.gz
  #   https://github.com/ameshkov/dnslookup/releases/download/v1.8.0/dnslookup-darwin-arm64-v1.8.0.tar.gz
  #   https://github.com/ameshkov/dnslookup/releases/download/v1.8.0/dnslookup-linux-amd64-v1.8.0.tar.gz
  #   https://github.com/ameshkov/dnslookup/releases/download/v1.8.0/dnslookup-linux-arm64-v1.8.0.tar.gz
  # generate url
  local url="${PACKAGE_CORE_RELEASE_DOWNLOAD}/$PACKAGE_CORE_VERSION/${name}-${platform}-${arch}-${PACKAGE_CORE_VERSION}.tar.gz"
  log::debug "[$(timestamp)][package][$name][$kernel][$arch] url: $url, file: ${tmp_file}, tmp_dir: $tmp_dir"

  # download
  log::info "[$(timestamp)][package][$name] downloading ..."
  os::download $tmp_file $url

  # extract
  log::info "[$(timestamp)][package][$name] extracting ..."
  os::extract $tmp_file

  # make executable
  log::info "[$(timestamp)][package][$name] making executable ..."
  chmod 755 $bin_file

  # install
  log::info "[$(timestamp)][package][$name] installing ..."
  sudo mv $bin_file $usr_bin_dir

  # clean
  log::info "[$(timestamp)][package][$name] cleaning ..."
  rm -rf $tmp_dir
}

export -f install
